### ISSUE TITLE
HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/downloaded/roberta-base/resolve/main/vocab.json

### ISSUE THREAD

**Issue by 1112321sfdsaf** [zhjohnchan/M3AE#1]
Hey,
Thanks very much for the excellent work and repo. 
When I run 'bash run_scripts/pretrain_m3ae.sh', I got the above exception. 
I tried to click this link and found that the link is unavailable. So, I replaced ' tokenizer=downloaded/roberta-base' in 'pretrain_m3ae.sh' with ' tokenizer=roberta-base', and got a successful run.
I would like to know if this operation is allowed.
![image](https://user-images.githubusercontent.com/75245666/190889700-3cd273b5-7698-4f05-8387-c89fa7cf2bfe.png)

**Comment by zhjohnchan** [comment]
Hi there,

Thanks for your attention. The operation is allowed since the downloaded RoBERTa model is the same one.

Best,
Zhihong

**Comment by 1112321sfdsaf** [comment]
Thank you very much for your reply.

**Comment by 1112321sfdsaf** [comment]
Hi again, I found that the default batch size per GPU is 32, and my own configuration seems far from that requirement, can you provide how much GPU memory is needed for 32 batches?

**Comment by zhjohnchan** [comment]
Hi,

I used A100-80G in my experiments.

Best,
Zhihong

**Comment by 1112321sfdsaf** [comment]
Thanks for your reply again.

**Comment by 1112321sfdsaf** [comment]
Hi, when preparing the MELINDA dataset using the link introduced in the paper "MELINDA: A Multimodal Dataset for Biomedical Experiment Method Classification", I got a 404 on the page, which means the link does not exist. So, how can I download this dataset to follow your excellent work?

**Comment by zhjohnchan** [comment]
Hi,

I request the dataset from the authors. I think you can send an e-mail to the author.

Best,
Zhihong

**Comment by 1112321sfdsaf** [comment]
Thanks for your suggestion.

**Comment by 1112321sfdsaf** [comment]
Hi, I'm back. 😅

When I download VQA-RAD on the official page, I found that the files are different from the description of this repo.
![image](https://user-images.githubusercontent.com/75245666/191047707-b8dad174-4f27-4f33-bac9-8d23350a2b38.png)
Moreover, reading the dataset paper, it seems just to divide the dataset into a training set and a test set. So, can you provide more details on the data splits including training, validation, and test sets? 

Thanks in advance.
