### ISSUE TITLE
Hello, when I debug M3AE, I found that the table value here is empty [ ], is there any problem with the code here? Or do I need to modify where

### ISSUE THREAD

**Issue by cl-red** [zhjohnchan/M3AE#12]
Hello, when I debug M3AE, I found that the tables value here is empty [], is there any problem with the code here? Or where do I need to modify? In addition, I want to know what the real output of the table here is, and what role does it play?
Thank you!

![8D6SLZ93DZD 6LU 8C5%DFY](https://user-images.githubusercontent.com/117440320/212820129-80a09d6f-5373-409a-80cb-a94f1ec587a9.png)

`        if len(names) != 0:
            tables = [
                pa.ipc.RecordBatchFileReader(pa.memory_map(f"{data_dir}/{name}.arrow", "r")).read_all()
                for name in names
                if os.path.isfile(f"{data_dir}/{name}.arrow")
            ]
            self.table_names = list()
            for i, name in enumerate(names):
                self.table_names += [name] * len(tables[i])
            self.table = pa.concat_tables(tables, promote=True)`

**Comment by zhjohnchan** [comment]
Hi,

Thanks for your attention.

Please follow the instruction to preprocess the data. If done, check the data path.

Best,
Zhihong
