### ISSUE TITLE
retrieval taking too long

### ISSUE THREAD

**Issue by stha-prashant** [zhjohnchan/M3AE#15]
evaluation on retrieval it s taking too long,(40 minutes for 756 examples)
 Changing the batch size for image preloading causes error. Is there a way to speed this up while using a single gpu?

**Comment by stha-prashant** [comment]
Also noticed that the retrieval is by default evaluating on val set and not the test set when test_only flag is true

**Comment by zhjohnchan** [comment]
Hi @stha-prashant,

Thanks for your attention! We could speed up the process by caching the image and text features. But this has not been implemented in our codebase.

Best,
Zhihong
