### ISSUE TITLE
The validation set of the VQA_RAD and the MELINDA dataset

### ISSUE THREAD

**Issue by GaryGuTC** [zhjohnchan/M3AE#17]
Hi Zhihong:
Thanks so much for your fantastic work.
I have checked the vqa_rad dataset and found that it only contains testset.json and trainset.json. Could you please provide the valset.json file?
Regarding the Melinda dataset, it seems that it may have been closed or unavailable, as I am unable to locate it. Could you also provide the Melinda dataset?

Thanks so much for your help!
Best regards

**Comment by languandong** [comment]
the same problem? did you resolve? can you help me? Thx

**Comment by GaryGuTC** [comment]
Hi
1. Please follow https://github.com/zhjohnchan/M3AE/issues/3#issuecomment-1258985614
2. Please follow https://github.com/zhjohnchan/M3AE/issues/8#issuecomment-1342267055

**Comment by M3Dade** [comment]
> Hi
> 
> 1. Please follow [Split for VQARAD #3 (comment)](https://github.com/zhjohnchan/M3AE/issues/3#issuecomment-1258985614)
> 2. Please follow [MELINDA dataset #8 (comment)](https://github.com/zhjohnchan/M3AE/issues/8#issuecomment-1342267055)

However, the vqa_rad dataset seems still lack val set

**Comment by 3514000142** [comment]
> > 你好
> > 
> > 1. 请关注 [VQARAD #3 的 Split（评论）](https://github.com/zhjohnchan/M3AE/issues/3#issuecomment-1258985614)
> > 2. 请关注 [MELINDA 数据集 #8 （评论）](https://github.com/zhjohnchan/M3AE/issues/8#issuecomment-1342267055)
> 
> 但是，vqa_rad 数据集似乎仍然缺少 val set
Hello, have you solved this problem?
