### ISSUE TITLE
Split for VQARAD

### ISSUE THREAD

**Issue by GanjinZero** [zhjohnchan/M3AE#3]
It seems that others use VQARAD with a train (3064) + test (451) set.
And it seems you have a dev set for VQARAD? What is your split config?

**Comment by GanjinZero** [comment]
Also why C4_abnormal is not used in MedVQA2019 train / dev / test?

**Comment by zhjohnchan** [comment]
Hi, following the settings of previous studies, I used the commonly used split (3064 + 451). I just duplicated the test set to unify the code interface. For MedVQA-2019, I followed this paper (https://www.nature.com/articles/s41598-021-98390-1) to set up the experiments and did not include C4_abnormal.

**Comment by GanjinZero** [comment]
got it
