### ISSUE TITLE
seems to be a subtle typo

### ISSUE THREAD

**Issue by baeseongsu** [zhjohnchan/M3AE#4]
Thank you for awesome work!

There seems be a subtle typo when calling SLAKE dataset in this repository and also in your paper.
Which one is correct, SLACK or SLAKE?

**Comment by zhjohnchan** [comment]
Hi, there! Thanks for your pointing it out. [SLAKE](https://www.med-vqa.com/slake/) is correct.

All the best,
Zhihong
