### ISSUE TITLE
MELINDA dataset

### ISSUE THREAD

**Issue by helenypzhang** [zhjohnchan/M3AE#5]
Dear author,

May I ask could you please share me the link of MELINDA dataset used in your paper?
The official website of this dataset collection pipeline and benchmark models is not available: https://github.com/PlusLabNLP/melinda.

Thank you so much for your help.

Best regards,
Yupei

**Comment by zhjohnchan** [comment]
Dear Yupei,

I requested this dataset from the authors of MELINDA. I think you could also send an e-mail.

Best,
Zhihong

**Comment by helenypzhang** [comment]
Dear Zhihong,

I emailed them but they haven't responded to me yet.
But thank you for your advice.

Best regards,
Yupei
