### ISSUE TITLE
missing roco_train_references.jsonl file

### ISSUE THREAD

**Issue by helenypzhang** [zhjohnchan/M3AE#6]
Dear Zhihong,

Thank you for your excellent work!

Since I haven't received the feedback of the medicat dataset authors, I would like to pre-training the model on roco dataset. But it seems that to pre-training the data of roco, roco_train_references.jsonl is needed. Is it generated by the prepro_medicat function? How can I get these files for pre-training on roco?
![image](https://user-images.githubusercontent.com/73587056/203738233-b5b29e7e-06cb-4464-8972-9ab3e125ee6d.png)

Many thanks,
Yupei

**Comment by zhjohnchan** [comment]
Dear Yupei,

These files are sourced from the medicat dataset. Please see the original medicat paper. To briefly explain this here, the medicat dataset contains the inline reference texts for the images of the roco dataset.

All the best,
Zhihong

**Comment by helenypzhang** [comment]
Got it! Thank you so much.
