### ISSUE TITLE
question about prepro/make_arrow.py

### ISSUE THREAD

**Issue by Adam-lxd** [zhjohnchan/M3AE#9]
Hi, I noticed a function `make_arrow_mimic_cxr` in `make_arrow.py`. Based on the description, M3AE only uses ROCO and MedICaT, so have you tried M3AE on the mimic dataset? I know it's also a large-scale medical image-text dataset. And if I can directly use `make_arrow.py` to mimic dataset without any modification, Thanks! :)

**Comment by zhjohnchan** [comment]
Hi,

Thanks for your attention. I have not tried MIMIC-CXR for M3AE. Yes, you can use it to make pyarrow dataset. You can also refer to [here](https://github.com/zhjohnchan/ARL/blob/527fe06a8811f8267a78ff82d45fd5c7136751b3/prepro/prepro_pretraining_data.py#L160) to pre-process MIMIC-CXR.

Best,
Zhihong

**Comment by Adam-lxd** [comment]
Thank you so much for your speedy reply! :)
